practika/polls/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('back/', views.index, name='index'),
    path('<int:rule_id>/', views.detail, name='detail'),
    path('delete/', views.delete),
    path('<int:rule_id>/delete/', views.delete_for_task_table),
    path('add/', views.add),
    path('<int:rule_id>/add/', views.add_for_task_table),
    path('<int:rule_id>/back/', views.back),
    path('update/<int:rule_id>/', views.update, name='list_upd'),
    path('update/<int:rule_id>/back/', views.back),
    path('update/<int:rule_id>/save/', views.save_update),
    path('<int:rule_id>/update/<int:task_id>/', views.update_for_task_table, name='detail_upd'),
    path('<int:rule_id>/update/<int:task_id>/save/', views.save_update_for_task_table),
    path('<int:rule_id>/update/<int:task_id>/back/', views.back_for_task_table)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

practika/practika/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

practika/polls/models.py
from django.db import models as m
import csv, os

class Value_for_type123(m.Model):
    def __init__(self):
        self.values_list = []
        self.read_types(os.getcwd() + '\\polls\\Типы заданий.csv')

    def read_types(self,file):  
        with open(file, newline='') as csvfile:
            reader = csv.reader(csvfile, delimiter=';', quotechar='|')
            for row in reader:
                self.values_list.append(row)
        self.values_list.pop(0)
        
    def get_type1_list(self):
        type1 = []
        for i in self.values_list:
            if not i[0] in type1 and i[0]!='Выберите':
                type1.append(i[0])
        return type1

    def get_type2_list(self, type1):
        type2 = []
        for i in self.values_list:
            if i[0] in type1 and i[1] not in type2 and i[1]!='Выберите':
                type2.append(i[1])
        return type2

    def get_type3_list(self, type1, type2):
        type3 = []
        for i in self.values_list:
            if i[0] in type1 and i[1] in type2 and i[2] not in type2 and i[2]!='Выберите':
                type3.append(i[2])
        return type3


class Dictionaries(m.Model):
    all_queues = ['Очередь 1','Очередь 2','Очередь 3','Очередь 4']
    all_operations = ['AND','OR']
    all_attributes = {'Тип задания 1': 'Справочник','Тип задания 2':'Справочник','Тип задания 3': 'Справочник','Тип клиента': 'Справочник',
                    'Признак запроса ОГВ': 'Логический','Признак соответствия суммы критериям НС': 'Логический','Статус': 'Справочник',
                    'Предпочитаемый способ связи': 'Справочник','Тип действия': 'Справочник','Результат действия': 'Строка'}
    all_operators = ['=','!=','in','not in','like','not like']
    all_values = {'Тип клиента': ('Юридическое лицо', 'Физическое лицо'),
                    'Статус': ('Открыто', 'В работе', 'Создан наряд во внешней системе', 'Отклонен', 'Завершен'),
                    'Предпочитаемый способ связи': ('SMS', 'Звонок', 'Email', 'Письмо', 'Информирование не требуется'),
                    'Тип действия': ('And',)}

    def get_operators(attribute):
        if Dictionaries.all_attributes[attribute] == 'Логический':
            return ['=','!=']
        elif Dictionaries.all_attributes[attribute] == 'Число':
            return ['=','!=','in','not in']
        else:
            return Dictionaries.all_operators

    def get_values(attribute_name,attribute1,attribute2): 
        val_list = Value_for_type123()
        if attribute_name == 'Тип задания 3':
            if attribute2:
                return val_list.get_type3_list(attribute1,attribute2)

            elif attribute1:
                return val_list.get_type2_list(attribute1)

            else:
                return val_list.get_type1_list()
        elif attribute_name == 'Тип задания 2':
            if attribute1:
                return val_list.get_type2_list(attribute1)

            else:
                return val_list.get_type1_list()
        elif attribute_name == 'Тип задания 1':
                return val_list.get_type1_list()
        elif attribute_name in Dictionaries.all_values.keys():
                return list(Dictionaries.all_values[attribute_name])
        elif Dictionaries.all_attributes[attribute_name] == 'Логический':
            return ['Да','Нет']
        else: return None


class Rule(m.Model):
    name = m.CharField('Название', max_length = 200)
    queue = m.CharField('Очередь', max_length = 200, choices = [(i,i) for i in Dictionaries.all_queues], default = '-')
    rule_range = m.IntegerField('Ранг',unique=True)
    creator = m.CharField('Пользователь, который создал правило', max_length = 20)
    updator = m.CharField('Пользователь, который последним изменил правило', max_length = 20)
    create_date = m.DateTimeField('Дата создания правила', auto_now=False, auto_now_add=True)
    update_date = m.DateTimeField('Дата последнего изменения правила',auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Правило"
        verbose_name_plural = "Список правил"



class Task(m.Model):
    rule = m.ForeignKey(Rule, on_delete = m.CASCADE, verbose_name="Правило")
    operation_type = m.CharField('Тип', max_length = 5, choices = [(i,i) for i in Dictionaries.all_operations], default = '-')
    attribute = m.CharField('Атрибут', max_length = 200, choices = [(i[0],i[0]) for i in list(Dictionaries.all_attributes.items())], default = '-')
    operator = m.CharField('Оператор', max_length = 200, choices = [(i,i) for i in Dictionaries.all_operators], default = '-')
    value = m.CharField('Значение', max_length = 200)

    def __str__(self):
        return self.operation_type + " " + self.attribute + " " + self.operator + " " + self.value

    class Meta:
        verbose_name = "Правило маршрутизации заданий"
        verbose_name_plural = "Правила маршрутизации заданий"

practika/polls/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Rule, Task, Dictionaries

def index(request):
    search = request.GET.get('search', None)
    search_text = request.GET.get('text', None)
    if search and search_text:
        if search == 'name':
            rule = Rule.objects.filter(name = search_text)
        elif search == 'queue':
            rule = Rule.objects.filter(queue = search_text)
            rule |= Rule.objects.filter(queue = 'Очередь '+str(search_text))
        return render(request,'polls/list.html', {'rule_list': rule, 'Dictionaries': Dictionaries, 'search': True})
  
    sort_type = request.GET.get('sort', None)
    if sort_type:
        rule_list = Rule.objects.order_by(sort_type)
    else:
        rule_list = Rule.objects.all()
    return render(request,'polls/list.html', {'rule_list': rule_list, 'Dictionaries': Dictionaries, 'search': False})

def detail(request, rule_id):
    try:
        rule = Rule.objects.get(id = rule_id)
        task = Task.objects.filter(rule = rule)

        sort_type = request.GET.get('sort', None)
        if sort_type:
            task = task.order_by(sort_type)
        
        new_operation = request.GET.get('operation', None)
        new_attribute = request.GET.get('attribute', None)
        new_operator = request.GET.get('operator', None)
        
        type1_attribute = None
        type2_attribute = None
        for i in task:
            if i.attribute == 'Тип задания 1':
                type1_attribute = i.value
            elif i.attribute == 'Тип задания 2':
                type2_attribute = i.value
    except:
        raise Http404("Правило не найдено")
    return render(request, 'polls/detail.html', {'rule': rule.name, 'task': task, 'Dictionaries': Dictionaries, 
                                                'attribute_temp': new_attribute, 'type1': type1_attribute, 
                                                'type2':type2_attribute, 'new_operation': new_operation, 'new_operator': new_operator})

def add(request):
    if request.method == "POST":
        rule = Rule()
        rule.name = request.POST.get("name_new")
        rule.queue = request.POST.get("queue_new")
        rule.rule_range = request.POST.get("rule_range_new")
        rule.creator = 'admin'
        rule.updator = 'admin'
        rule.save()
    return HttpResponseRedirect("/polls/")

def add_for_task_table(request, rule_id):
    if request.method == "POST":
        task = Task()
        task.rule = Rule.objects.get(id = rule_id)
        task.operation_type = request.POST.get("operation_new")
        task.attribute = request.POST.get("attribute_new")
        task.operator = request.POST.get("operator_new")
        task.value = request.POST.getlist("value_new")
        task.save()
    return HttpResponseRedirect("/polls/"+str(rule_id)+"/")

def update(request, rule_id):
    rule_list = Rule.objects.all()
    return render(request,'polls/list_upd.html', {'rule_list': rule_list, 'Dictionaries': Dictionaries, 'id_to_update': rule_id})
    
def save_update(request, rule_id):  
    rule = Rule.objects.get(id = rule_id)
    if request.method == "POST":
        rule.name = request.POST.get("name")
        rule.queue = request.POST.get("queue")
        rule.rule_range = request.POST.get("rule_range")
        rule.creator = 'admin'
        rule.updator = 'admin'
        rule.save()
    rule_list = Rule.objects.order_by('name')
    return HttpResponseRedirect("/polls/")

def update_for_task_table(request, rule_id, task_id):
    rule = Rule.objects.get(id = rule_id)
    task = Task.objects.filter(rule = rule)
    upd_task = Task.objects.filter(id = task_id)
    type1_attribute = None
    type2_attribute = None
    for i in task:
        if i.attribute == 'Тип задания 1':
            type1_attribute = i.value
        elif i.attribute == 'Тип задания 2':
            type2_attribute = i.value
    attribute2 = request.GET.get('attribute', upd_task[0].attribute)
    return render(request,'polls/detail_upd.html', {'rule': rule.name, 'task': task, 'Dictionaries': Dictionaries, 'attribute_temp': attribute2, 
                                                'type1': type1_attribute, 'type2': type2_attribute, 'id_to_update': task_id})
    
def save_update_for_task_table(request, rule_id, task_id):  
    task = Task.objects.get(id = task_id)
    if request.method == "POST":
        task.operation_type = request.POST.get("operation")
        task.attribute = request.POST.get("attribute")
        task.operator = request.POST.get("operator")
        task.value =  str(request.POST.getlist("value"))
        task.save()
    return HttpResponseRedirect("/polls/"+str(rule_id)+"/")

def delete(request):
    print(request)
    try:
        if request.method == "POST":
            rule_del = request.POST.getlist('checks')

            for i in rule_del:

                Rule.objects.filter(id=i).delete()
        return HttpResponseRedirect("/polls/")
    except Rule.DoesNotExist:
        return Http404("Rule not found")

def delete_for_task_table(request,rule_id):
    try:
        if request.method == "POST":
            task_del = request.POST.getlist('checks')
            for i in task_del:
                Task.objects.filter(id=i).delete()
        return HttpResponseRedirect("/polls/"+str(rule_id)+"/")
    except Rule.DoesNotExist:
        return Http404("Rule not found")

def back(request,rule_id):
    return HttpResponseRedirect("/polls/")

def back_for_task_table(request,rule_id,task_id):
    return HttpResponseRedirect("/polls/"+str(rule_id)+"/")

practika/polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block title %}{{rule}}{% endblock %}

{% block content %}
    {% load choose_operators %}

    <h2>{{rule}}</h2>

    <table class="table">
        <form action="delete/" method="post">
            {% csrf_token %}
            <thead class="table-head">
                <tr>
                    <th><input type="submit" class="submit_button" value="Удалить"></th> 
                    <th onclick="location.href='?sort=operation_type'">Тип</th>
                    <th onclick="location.href='?sort=attribute'">Атрибут</th>
                    <th onclick="location.href='?sort=operator'">Оператор</th>
                    <th>Значение</th>
                    <th></th>
                </tr>
            </thead>

            {% if task %}
                {% for t in task %}
                    <tr class="row">
                        <td><input type="checkbox"  value="{{t.id}}" name="checks"></td>
                        <td><p>{{t.operation_type}}</p></td>
                        <td><p>{{t.attribute}}</p></td>
                        <td><p>{{t.operator}}</p></td>
                        <td>
                            {% make_values_list t.value as list_value %}
                            {% for i in list_value %}
                                <p>{{i}}</p>
                            {% endfor %}
                        </td>
                        <td><a class="a_button" href="update/{{t.id}}">Изменить</a></td>                       
                    </tr>
       
                {% endfor %}
            {% endif %}
        </form>
        <form action="add/" method="post">
            {% csrf_token %}
            <tr class="row">
                <td></td>
                <td>
                    <select id="t_operation" name="operation_new" onchange="location.href='?operation='+value+'&';">
                        <option value="">Не выбрано</option>
                        {% for i in Dictionaries.all_operations %}
                            <option value="{{i}}" {% if new_operation == i %} selected="selected" {% endif %}>{{i}}</option>
                        {% endfor %}
                    </select>
                </td>
                <td>
                    <select id="t_attribute_new" name="attribute_new" onchange="location.href+='attribute='+value+'&';">
                        <option value="">Не выбрано</option>
                        {% for i in Dictionaries.all_attributes %}
                            {% check_attribute i type1 type2 as check_attr %}
                            {% if check_attr %}
                                <option value="{{i}}" {% if attribute_temp == i %} selected="selected" {% endif %} >{{i}}</option>
                            {% endif %} 
                        {% endfor %}
                    </select>
                </td>
                <td>
                    <select id="t_operator_new" name="operator_new" onchange="location.href+='operator='+value;">
                        <option value="">Не выбрано</option>
                        {% if attribute_temp %}
                            {% choose_operators attribute_temp as op %}
                            {% for i in op %}
                                <option value="{{i}}" {% if new_operator == i %} selected="selected" {% endif %}>{{i}}</option>
                            {% endfor %}
                        {% endif %} 
                   </select> 
                </td>
                <td>
                    {% if attribute_temp %}
                        {% choose_values attribute_temp type1 type2 as val %}
                        {% if val and new_operator != 'like' and new_operator != 'not like' %}
                            <select class="sel_t_value" name="value_new" {% if new_operator == 'in' or new_operator == 'not in' %} multiple size=3 {% endif %} >
                                <option value="">Не выбрано</option>
                                    {% for i in val %}
                                        <option value="{{i}}">{{i}}</option>
                                    {% endfor %}
                            </select> 
                        {% else %}
                            <input type="text" class="inp_rule_name" name="value_new"/>
                        {% endif %}
                    {% endif %} 
                </td>
                <td><input type="submit" class="submit_button" value="Сохранить"></td>
            </tr>
        </form>
    </table>
    <br><br>
    <div class="back">
        <form action="back/">
            <input type="submit" class="submit_button" class="back" value="Назад">
        </form>
    </div>
{% endblock %}

practika/polls/templates/polls/detail_upd.html
{% extends 'base.html' %}

{% block title %}{{rule}}{% endblock %}

{% block content %}
    {% load choose_operators %}

    <h2>{{rule}}</h2>

    <table class="table">
        
            <thead class="table-head">
                <tr>
                    <th><input type="submit" class="submit_button hide" value="Удалить"></th> 
                    <th>Тип</th>
                    <th>Атрибут</th>
                    <th>Оператор</th>
                    <th>Значение</th>
                    <th></th>
                </tr>
            </thead>

            {% if task %}
                {% for t in task %}
                    {% if t.id != id_to_update %}
                        <tr class="row">
                            <td><input type="checkbox"  value="{{t.id}}" name="checks"></td>
                            <td><p>{{t.operation_type}}</p></td>
                            <td><p>{{t.attribute}}</p></td>
                            <td><p>{{t.operator}}</p></td>
                            <td>
                                {% make_values_list t.value as list_value %}
                                {% for i in list_value %}
                                    <p>{{i}}</p>
                                {% endfor %}
                            </td>
                            <td><a class="a_button" href="update/{{t.id}}">Изменить</a></td>                       
                        </tr>
                    {% else %}
                        <tr class="row">
                            <form action="save/" method="post">
                                {% csrf_token %}
                                <td><input type="checkbox" value="{{t.id}}" name="checks"></td>
                                <td>
                                    <select class="sel_t_operation" name="operation">
                                        {% for i in Dictionaries.all_operations %}
                                            {% if i == t.operation_type %}
                                                <option selected value="{{i}}">{{i}}</option>
                                            {% else %}
                                                <option value="{{i}}">{{i}}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                </td>
                                <td>
                                    <select class="sel_t_attribute" name="attribute" onchange="location.href='?attribute='+value;">
                                        {% for i in Dictionaries.all_attributes %}
                                            {% check_attribute i type1 type2 as check_attr %}
                                            {% if check_attr %}
                                                
                                                <option value="{{i}}" {% if attribute_temp == i %} selected="selected" {% endif %} >{{i}}</option>
                                                

                                            {% endif %} 
                                        {% endfor %}
                                    </select>
                                </td>
                                <td>
                                    <select class="sel_t_operator" name="operator">
                                        {% if attribute_temp %}
                                            {% choose_operators attribute_temp as op %}
                                            {% for i in op %}
                                            {% if i == t.operator %}
                                                <option selected value="{{i}}">{{i}}</option>
                                                {% else %}
                                                <option value="{{i}}">{{i}}</option>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %} 
                                    </select>
                                </td>
                                <td>
                                    <select class="sel_t_value" name="value" {% if t.operator == 'in' or t.operator == 'not in' %} multiple size=3 {% endif %} >
                                        {% make_values_list t.value as list_value %}
                                        {% if attribute_temp %}
                                            {% choose_values attribute_temp type1 type2 as val %}
                                            {% for i in val %}
                                                {% if i in list_value %}
                                                    <option selected value="{{i}}">{{i}}</option>
                                                {% else %}
                                                    <option value="{{i}}">{{i}}</option>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %} 
                                    </select>
                                </td>
                                <td><input type="submit" class="submit_button" value="Сохранить"></td>
                            </form>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% endif %}
    
    </table>
    <br><br>
    <div class="back">
        <form action="back/">
            <input type="submit" class="submit_button" class="back" value="Отмена">
        </form>
    </div>
{% endblock %}

practika/polls/templates/polls/list.html
{% extends 'base.html' %}

{% block title %}Правила маршрутизации{% endblock %}

{% block content %}
    
    <h2>Правила маршрутизации</h2>

    <div class='search'>
        <select class="sel_search" onchange="location.href='?search='+value;">
            <option value="">Не искать</option>
            <option value="name" {% if request.GET.search == "name" %} selected="selected" {% endif %}>Поиск по названию</option>
            <option value="queue" {% if request.GET.search == "queue" %} selected="selected" {% endif %}>Поиск по очереди</option>
        </select>
        <p>&emsp;&emsp;</p> 
        <input type="text" class="inp_search" onchange="location.href+='&text='+value;"/>
    </div>

    <table class="table">
        <form action="delete/" method="post">
            {% csrf_token %}
            <thead class="table-head">
                <tr>
                    <th><input type="submit" class="submit_button" value="Удалить"></th> 
                    <th onclick="location.href='?sort=name'">Название</th>
                    <th onclick="location.href='?sort=queue'">Очередь</th>
                    <th onclick="location.href='?sort=rule_range'">Ранг</th>
                    <th></th>
                </tr>
            </thead>
        
            {% if rule_list %}
                {% for a in rule_list %}
                    <tr class="row">
                        <td><input type="checkbox"  value="{{a.id}}" name="checks"></td>
                        <td><a class="rule_ref" href="{% url 'polls:detail' a.id %}">{{a.name}}</a></td>
                        <td><p>{{a.queue}}</p></td>
                        <td><p>{{a.rule_range}}</p></td>
                        <td><a class="a_button" href="{% url 'polls:list_upd' a.id %}">Изменить</a></td>                     
                    </tr>
                {% endfor %}
            {% endif %}
        </form>      
        
        <form action="add/" method="post">
            {% csrf_token %}
            <tr class="row">
                <td></td>
                <td><input type="text" class="inp_rule_name" name="name_new"/></td>
                <td>
                    <select class="sel_rule_queue" name="queue_new">
                        {% for i in Dictionaries.all_queues %}
                            <option value="{{i}}">{{i}}</option>
                        {% endfor %}
                    </select>
                </td>
                <td><input type="number" class="inp_rule_range" name="rule_range_new"/></td>
                <td><input type="submit" class="submit_button" value="Сохранить"></td>  
            </tr>
        </form>
        
    </table>

{% endblock %}

practika/polls/templates/polls/list_upd.html
{% extends 'base.html' %}

{% block title %}Правила маршрутизации{% endblock %}

{% block content %}
    
    <h2>Правила маршрутизации</h2>
    
    <table class="table">

        <thead class="table-head">
            <tr>
                <th><input type="submit" class="submit_button hide" value="Удалить"></th> 
                <th onclick="location.href='?sort=name'">Название</th>
                <th onclick="location.href='?sort=queue'">Очередь</th>
                <th onclick="location.href='?sort=rule_range'">Ранг</th>
                <th></th>
            </tr>
        </thead>
        {% if rule_list %}
            {% for a in rule_list %}
                {% if a.id != id_to_update %}
                    <tr class="row">
                        <td><input type="checkbox"  value="{{a.id}}" name="checks"></td>
                        <td><a class="rule_ref" href="{% url 'polls:detail' a.id %}">{{a.name}}</a></td>
                        <td><p>{{a.queue}}</p></td>
                        <td><p>{{a.rule_range}}</p></td>
                        <td><a class="a_button" href="{% url 'polls:list_upd' a.id %}">Изменить</a></td>                     
                    </tr>
                {% else %}
                <tr class="row">
                    <form action="save/" method="post">
                        {% csrf_token %}
                        <td><input type="checkbox"  value="{{a.id}}" name="checks"></td>
                        <td><input type="text" class="inp_rule_name" name="name" value="{{a.name}}"/></td>
                        <td>
                            <select class="sel_rule_queue" name="queue">
                            {% for i in Dictionaries.all_queues %}
                                {% if i == a.queue %}
                                    <option selected value="{{i}}">{{i}}</option>
                                {% else %}
                                    <option value="{{i}}">{{i}}</option>
                                {% endif %}
                            {% endfor %}
                            </select>
                        </td>
                        <td><input type="number" class="inp_rule_range" name="rule_range" value="{{a.rule_range}}"/></td>
                        <td><input type="submit" class="submit_button" value="Сохранить"></td>     
                    </form>                     
                </tr>
                {% endif %}
            {% endfor %}
        {% endif %}
 
        
    </table>  
    <br><br>
    <div class="back">
        <form action="back/">
            <input type="submit" class="submit_button" class="back" value="Назад">
        </form>
    </div>
{% endblock %}